name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Build Docker image
    - name: Build Docker Image
      run: docker build --no-cache -t sales-api .

    # 3. Run container
    - name: Run Container
      run: docker run -d -p 8000:8000 --name test-container sales-api

    # 4. Wait for API to be ready
    - name: Wait for API
      run: |
        echo "Waiting for API to start..."
        for i in {1..12}; do
          if curl -f http://localhost:8000; then
            echo "API is up!"
            exit 0
          fi
          echo "Retrying in 5 seconds..."
          sleep 5
        done
        echo "API failed to start"
        docker logs test-container
        exit 1
    # 4.1. Model test
    - name: Validate prediction value
      run: |
        response=$(curl -s -X POST http://localhost:8000/predict \
        -H "Content-Type: application/json" \
        -d '{
          "Weight": 10,
          "FatContent": "Low Fat",
          "ProductVisibility": 0.05,
          "ProductType": "Dairy",
          "MRP": 200,
          "OutletSize": "Medium",
          "LocationType": "Tier 1",
          "OutletType": "Supermarket Type1",
          "Years_Operation": 10
        }')
    
        echo $response
    
        # Extract number
        pred=$(echo $response | grep -o '[0-9.]*')
    
        echo "Prediction: $pred"
    
        # Basic sanity check
        if [ -z "$pred" ]; then
          echo "No prediction returned"
          exit 1
        fi
    # 5. Show container logs (for debugging)
    - name: Show container logs
      run: docker logs test-container

    # 6. Stop container (cleanup)
    - name: Stop container
      if: always()
      run: docker stop test-container
