name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t sales-api .

    - name: Run Container
      run: docker run -d -p 8000:8000 sales-api

    - name: Wait for app to start
      run: sleep 20

    - name: Check running containers
      run: docker ps

    - name: Show container logs
      run: docker logs $(docker ps -q)

    - name: Test API
      run: |
        curl -f http://localhost:8000 || exit 1
